### ISSUE TITLE
Screen fills up: need a way to trim the list after a certain pint

### ISSUE THREAD

**Issue by MiketheChap** [protostax/ProtoStax_ISS_Tracker#6]
The list of positions can accumulate so many positions that the screen eventually fills up. I noted this on the Hackster project page. I paid a programmer because my Python skills aren't good enough to create the suggested "circular or ring buffer". I'm not sure how to share that code but it seems to be working well on my setup. I'm happy to share the code.

**Comment by sridharrajagopal** [comment]
Fantastic Mike! I'll follow up with you on how we can pull in the changes here! 

Best, 
Sridhar

**Comment by sridharrajagopal** [comment]
Hi Mike, 

Just looked at the implementation. It will suffice, as the total size of the buffer is not too big. There are more efficient implementations possible, but this works for now! 

Your branch also doesn't have some of the changes that have been made since you forked it, thanks to jplegat and matkier's contributions. (making it a service, and disassociating the display interval with the data fetch interval (which can be done more often). 

If you can ask melcasipit to first pull in the changes from the main protostax branch along with his changes, and then create a pull request, then I can merge those changes in! 

Thanks,
Sridhar

**Comment by sridharrajagopal** [comment]
Ok, I just quickly pulled in the changes myself (and did a little cleanup - renamed LIMIT to DATA_LIMIT, and comments). 

I've also added the list of contributors to top comment.   

Please go ahead and update your fork to pull in the latest changes - there have been changes made by jplegat and matkier that you are missing. These changes will help you. 

Thanks,
Sridhar
