### ISSUE TITLE
screen

### ISSUE THREAD

**Issue by xyz14** [protostax/ProtoStax_ISS_Tracker#7]
hello
i don't have a e-paper "screen" but i have a 7 inch raspberry pi touchscreen. Is there any way i can use that to see iss position?

**Comment by sridharrajagopal** [comment]
You most certainly can! But that would mean rewriting the iss.py to create a GUI that you can display on your touch screen or TV, instead of the ePaper. There are many packages and options for you to choose from. Raspberry Pi Projects page has a tutorial that uses guizero Python package - this would be a good place to get started. 

https://projects.raspberrypi.org/en/projects/getting-started-with-guis

Cheers, 
Sridhar
PS - I'm going to close this issue, but feel free to open another one for other questions you may have!
